### ISSUE TITLE
More fixes

### ISSUE THREAD

**Issue by DannySS123** [kir-dev/konzisite-frontend#136]
- [x] **WONTFIX** popular opinion: this is too much and makes little sense:
![image](https://user-images.githubusercontent.com/65909866/221051732-3b0be180-c580-4a70-8533-afb137e5c83c.png)
- [x] pageHeading top margin (could be same as bottom)
- [x] **WONTFIX** navbar button action colors?
- [x] konzi rating csúszka gomb szín
- [x] targetGroup names in 2 places...
- [x] **WONTFIX** the site body isnt 100%, when there is no scrollbar it looks strange 
- [x] space above footer
- [x] rename R components
- [x] konzi request list item jobb alsó szöveg padding
- [x] margin for nincsenek...
- [x] new konzi back button should go to the prev page
- [x] page heading bottom margin

**Comment by Tschonti** [comment]
are we sure we don't want to fix the navbar border? multiple people suggested it
