### ISSUE TITLE
Mobile landscape view

### ISSUE THREAD

**Issue by DannySS123** [kir-dev/konzisite-frontend#210]
The navbar has some problems:

![image](https://user-images.githubusercontent.com/65909866/228797784-cadec979-fb37-4151-8ba7-530ab93df6bf.png)

**Comment by Tschonti** [comment]
This is not a mobile specific bug, the navbar simply switches to the dropdown version below ~768px but it's much longer than that. So that breakpoint should be changed to fix the bug
