### ISSUE TITLE
EditConsultationPage validation weirdness

### ISSUE THREAD

**Issue by Tschonti** [kir-dev/konzisite-frontend#86]
- If you edit a consultation that has started or ended, you cannot save it because the start date will throw a validation error
- Sometimes the submit button stays disabled, even though there are no red errors (don't remember how to reproduce it, sorry)

**Comment by DannySS123** [comment]
and this: 

![image](https://user-images.githubusercontent.com/65909866/216770210-becef17a-af6c-4753-88e9-1c34a39cacc6.png)
